# Generated by Django 4.0.3 on 2022-03-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='id_video',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
