# Generated by Django 4.0.3 on 2022-03-26 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_accounts_alter_account_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accounts',
        ),
    ]
