# Generated by Django 4.0.3 on 2022-03-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_account_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
