# Generated by Django 4.0.3 on 2022-03-25 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_account_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='account',
            old_name='id_link',
            new_name='idLink',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='id_name',
            new_name='idName',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='id_link',
            new_name='idLink',
        ),
        migrations.RemoveField(
            model_name='account',
            name='account',
        ),
        migrations.AddField(
            model_name='account',
            name='accountType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.accounttype'),
        ),
    ]
