# Generated by Django 4.0.3 on 2022-03-25 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_account_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='idLink',
            new_name='id_link',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='idName',
            new_name='id_name',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='idLink',
            new_name='id_link',
        ),
    ]
